Update build files

diff --git a/buildroot-build b/buildroot-build
--- a/buildroot-build
+++ b/buildroot-build
@@ -1,10 +1,27 @@
 #!/bin/bash
 
-source secrets
-
-echo "Spotify ClientID is $SPOTIFY_CLIENT_ID"
+if [ -f "./secrets" ]; then
+  	source ./secrets
+	echo "Spotify ClientID is $SPOTIFY_CLIENT_ID"
+else
+	echo "No secrets file found, create it by filling in secrets.template and changing name to secrets."
 
 cd ./buildroot
-make BR2_EXTERNAL=../hifiberry-os/buildroot
+if [ $? -ne 0 ]; then
+  echo "Failed to change directory to ./buildroot, did you run setup.sh?"
+  exit 1
+fi
 
+echo "Building rootfs"
+make BR2_EXTERNAL=../hifiberry-os/buildroot
+if [ $? -ne 0 ]; then
+  echo "Make command failed."
+  exit 1
+fi
+
+echo "Copying rootfs.tar to output file."
 cp ./output/images/rootfs.tar ../output
+if [ $? -ne 0 ]; then
+  echo "Failed to copy rootfs.tar."
+  exit 1
+fi
diff --git a/buildroot-menuconfig b/buildroot-menuconfig
--- a/buildroot-menuconfig
+++ b/buildroot-menuconfig
@@ -1,3 +1,12 @@
 #!/bin/bash
 cd ./buildroot
+if [ $? -ne 0 ]; then
+  echo "Failed to change directory to ./buildroot."
+  exit 1
+fi
+
 make BR2_EXTERNAL=../hifiberry-os/buildroot/ menuconfig
+if [ $? -ne 0 ]; then
+  echo "Make menuconfig failed."
+  exit 1
+fi
diff --git a/kernel-build b/kernel-build
--- a/kernel-build
+++ b/kernel-build
@@ -1,19 +1,55 @@
 #!/bin/bash
+
+
 cd ./ti-sdk/board-support/ti-linux-kernel-6.1.46+gitAUTOINC+1d4b5da681-g1d4b5da681/
+if [ $? -ne 0 ]; then
+  echo "Failed to change directory, did you run setup.sh?"
+  exit 1
+fi
+
 export PATH=../../external-toolchain-dir/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/bin:$PATH
+if [ $? -ne 0 ]; then
+  echo "Failed to set PATH."
+  exit 1
+fi
 
 echo "Compiling Kernel"
 make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf- uImage LOADADDR=0x80008000
+if [ $? -ne 0 ]; then
+  echo "Kernel compilation failed."
+  exit 1
+fi
 
 echo "Compiling modules"
 make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf- modules
+if [ $? -ne 0 ]; then
+  echo "Modules compilation failed."
+  exit 1
+fi
 
 echo "Creating Roomplayer DTB from DTS"
 make DTC_FLAGS=-@ ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf- roomplayer.dtb
+if [ $? -ne 0 ]; then
+  echo "DTB creation failed."
+  exit 1
+fi
 
 echo "Copying DTB and Images to output directory"
 cp ./arch/arm/boot/*Image ../../../output
+if [ $? -ne 0 ]; then
+  echo "Failed to copy kernel images to the output directory."
+  exit 1
+fi
+
 cp ./arch/arm/boot/dts/roomplayer.dtb ../../../output
+if [ $? -ne 0 ]; then
+  echo "Failed to copy roomplayer.dtb to the output directory."
+  exit 1
+fi
 
 echo "Installing modules to overlay directory."
 make ARCH=arm INSTALL_MOD_PATH=../../../overlay/usr modules_install
+if [ $? -ne 0 ]; then
+  echo "Failed to install kernel modules."
+  exit 1
+fi
diff --git a/kernel-menuconfig b/kernel-menuconfig
--- a/kernel-menuconfig
+++ b/kernel-menuconfig
@@ -1,4 +1,18 @@
 #!/bin/bash
 cd ./ti-sdk/board-support/ti-linux-kernel-6.1.46+gitAUTOINC+1d4b5da681-g1d4b5da681/
-export PATH=../../external-toolchain-dir/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/:$PATH
+if [ $? -ne 0 ]; then
+  echo "Failed to change directory, did you run setup.sh?"
+  exit 1
+fi
+
+export PATH=../../external-toolchain-dir/arm-gnu-toolchain-11.3.rel1-x86_64-arm-none-linux-gnueabihf/bin:$PATH
+if [ $? -ne 0 ]; then
+  echo "Failed to set the PATH for the cross-toolchain."
+  exit 1
+fi
+
 make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabihf- menuconfig
+if [ $? -ne 0 ]; then
+  echo "Make menuconfig failed."
+  exit 1
+fi
